### ISSUE TITLE
vim-mode-plus config lives wrong level in config.cson.

### ISSUE THREAD

**Issue by t9md** [slavaGanzin/config#1]
While I was browsing your config, I noticed your vim-mode-plus config is pulled to upper-level(=package level).

like this.
https://github.com/slavaGanzin/config/blob/ab933c09be7e8f610210f8b9f4a6f09a5573140c/.atom/config.cson#L21-L23

Not sure why, these are garbage unless moved to under `vim-mode-plus` field.

**Comment by slavaGanzin** [comment]
Fixed. Thanks a lot.
